SHOW DATABASES;
USE AISWARYA;
SHOW TABLES;
CREATE TABLE STUDENTS(STUDENT_ID INT PRIMARY KEY,NAME VARCHAR(50),AGE INT,DEPARTMENT VARCHAR(30),ENROLLMENTDATE DATE);
DESC STUDENTS;
ALTER TABLE STUDENTS ADD EMAIL VARCHAR(50);

