SHOW DATABASES;
USE AISWARYA;
SHOW TABLES;
DESC STUDENTS;
DROP TABLE STUDENTS;
SHOW TABLES;
CREATE TABLE STUDENT(STD_ID INT PRIMARY KEY, NAME VARCHAR(50),AGE INT,DEPT VARCHAR(30),ENROLLMENTDATE DATE);
DESC STUDENT;
ALTER TABLE STUDENT DROP DEPT;
ALTER TABLE STUDENT ADD EMAIL VARCHAR(50);
INSERT INTO STUDENT VALUES(1,"ANU",25,'2024-05-14',"ANU@GMAIL.COM"),(2,"RAM",26,'2024-04-07',"RAM@GMAIL.COM"),(3,"SAM",30,'2024-08-21',"SAM@GMAIL.COM");
SELECT *FROM STUDENT;
UPDATE STUDENT SET AGE=22 WHERE STD_ID=3;
INSERT INTO STUDENT VALUES(4,"GOP",17,'2024-06-01',"GOP@GMAIL.COM");
DELETE FROM STUDENT WHERE AGE<18;
SELECT *FROM STUDENT WHERE AGE<18;


